### ISSUE TITLE
Doesn't seem to work.

### ISSUE THREAD

**Issue by ghost** [macx/google-photos-dark-mode#1]
Unfortunately this doesn't seem to work for me. It only makes some areas a light gray color.
![photos](https://user-images.githubusercontent.com/107957769/174897837-93c5326b-8b6b-4dac-a95b-6815e787e1f4.png)

**Comment by macx** [comment]
@SafariBat  Sorry, my fault. I fixed the colors settings. Version [v1.1.0](https://github.com/macx/google-photos-dark-mode/releases/tag/v1.1.0) is now working. Please update it via the Extension and tell me, if it's working.
